# Generated by Django 2.1 on 2018-08-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180821_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartgoods',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
