# Generated by Django 2.1 on 2018-08-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=1, max_length=20, verbose_name='图片样式'),
            preserve_default=False,
        ),
    ]
