# Generated by Django 2.1 on 2018-08-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='主图'),
        ),
    ]
