# Generated by Django 2.1 on 2018-08-18 03:35

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180817_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='picture',
        ),
        migrations.AddField(
            model_name='goods',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_thumb, verbose_name='主图'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='密码不能少于8位')], verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='用户名不能少于6位')], verbose_name='用户名'),
        ),
    ]
